src/Entity/Slider.php
<?php

namespace App\Entity;

use App\Repository\SliderRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SliderRepository::class)]
class Slider
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $button_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $button_text = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getButtonLink(): ?string
    {
        return $this->button_link;
    }

    public function setButtonLink(?string $button_link): static
    {
        $this->button_link = $button_link;

        return $this;
    }

    public function getButtonText(): ?string
    {
        return $this->button_text;
    }

    public function setButtonText(?string $button_text): static
    {
        $this->button_text = $button_text;

        return $this;
    }
}

src/Form/SliderType.php
<?php

namespace App\Form;

use App\Entity\Slider;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class SliderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre',
                'required' => true,
                'constraints' => [
                    new Assert\Length(['max' => 255])
                ]
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Contenu',
                'required' => true,
                'constraints' => [
                    new Assert\Length(['max' => 255])
                ]
            ])
            ->add('button_link',UrlType::class, [
                'label' => 'Lien du bouton',
                'required' => false,
                'constraints' => [
                    new Assert\Length(['max' => 255])
                ]
            ])
            ->add('button_text', TextType::class, [
                'label' => 'Texte du bouton',
                'required' => false,
                'constraints' => [
                    new Assert\Length(['max' => 255])
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Slider::class,
        ]);
    }
}

src/Controller/SliderController.php
<?php

namespace App\Controller;

use App\Entity\Slider;
use App\Form\SliderType;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Bundle\PaginatorBundle\KnpPaginatorBundle;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\PaginatorInterface;
use PHPUnit\Util\Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SliderController extends AbstractController
{
    #[Route('/admin/slider', 'slider_show')]
    public function read(EntityManagerInterface $entityManager, PaginatorInterface $paginator, Request $request) : Response
    {
        $sliderRepo = $entityManager->getRepository(Slider::class);
        $sliders = $sliderRepo->findAll();
        $data = $paginator->paginate(
            $sliders, $request->query->getInt('page', 1),10
        );
        return $this->render('slider/index.html.twig', [
            'sliders' => $data,
        ]);
    }

    #[Route('/admin/slider/create', name: 'slider_form')]
    public function create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $slider = new Slider();
        $form = $this->createForm(SliderType::class, $slider);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $entityManager->persist($slider);
            $entityManager->flush();
            $this->addFlash('success', 'Les informations du slider ont bien été enregistrées');
            return $this->redirectToRoute('slider_show');
        }
        return $this->render('slider/sliderCreate.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/admin/slider/update/{id}', 'slider_update')]
    public function update(Request $request, EntityManagerInterface $entityManager, $id) :Response
    {
        $sliderRepo = $entityManager->getRepository(Slider::class);
        $slider = $sliderRepo->find($id);

        if (!$slider){
            $this->createNotFoundException('Aucun slider trouvé pour l\'id '.$id);
        }
        $form = $this->createForm(SliderType::class, $slider);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $entityManager->flush();
            $this->addFlash('success', 'Les modifications du slider ont été enregistrées');

            return $this->redirectToRoute('slider_show');
        }
        return $this->render('slider/sliderEdit.html.twig', [
            'form' => $form->createView(),
            'slider' => $slider
        ]);
    }

    #[Route('/admin/slider/delete/{id}', name: 'slider_delete')]
    public function delete(Request $request, EntityManagerInterface $entityManager, $id) : Response
    {
        $sliderRepo = $entityManager->getRepository(Slider::class);
        $slider = $sliderRepo->find($id);

        if (!$slider) {
            throw $this->createNotFoundException('Aucun slider trouvé pour l\'id '.$id);
        }

        $entityManager->remove($slider);
        $entityManager->flush();

        $this->addFlash('success', 'Le slider a été supprimé');
        return $this->redirectToRoute('slider_show');
    }

}

templates/slider/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin | Slider{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
            <span class="font-medium">{{ message }}</span>
        </div>
    {% endfor %}



        <div class="relative overflow-x-auto flex justify-center items-center mt-2">
            <table class="w-[80%] text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Titre
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Contenu
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Texte bouton
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Lien bouton
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Action
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for slider in sliders  %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ slider.title }}
                        </th>
                        <td class="px-6 py-4">
                            {{ slider.content }}
                        </td>
                        <td class="px-6 py-4">
                            {{ slider.buttonText }}
                        </td>
                        <td class="px-6 py-4">
                            {{ slider.buttonLink }}
                        </td>
                        <td class="px-6 py-4 text-center flex">
                            <a href="{{ path('slider_delete', {'id': slider.id}) }}" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-4 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Supprimer</a>
                            <a href="{{ path('slider_update', {'id': slider.id}) }}" class="focus:outline-none text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Modifier</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
            <div class="navigation flex justify-center mb-8">{{ knp_pagination_render(sliders) }}</div>

{% endblock %}

templates/slider/sliderCreate.html.twig
{% extends 'base.html.twig' %}

{% block title %}Slider | Ajout{% endblock %}


{% block body %}
    <div class="flex justify-center ">
        {{ form_start(form) }}
        {{ form_rest(form) }}
        <button class="bg-emerald-950">Submit</button>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/slider/sliderEdit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Slider | Ajout{% endblock %}


{% block body %}
    <div class="flex justify-center ">
        {{ form_start(form) }}
        {{ form_rest(form) }}
        <button class="bg-emerald-950">Submit</button>
        {{ form_end(form) }}
    </div>

{% endblock %}